name: Github Packages
on:
  push:
    branches: [main]
jobs:
  build:
    name: 'Build and Publish'
    runs-on: ubuntu-latest
    steps:
      - name: Git config
        run: git config --global user.email "${{ secrets.GIT_EMAIL }}" && git config --global user.name "${{ secrets.GIT_USERNAME }}"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup configuration for GH Packages
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@dankreiger'

      - name: Install
        run: yarn

      - name: Lerna Bootstrap
        run: yarn lerna bootstrap

      - name: Test packages
        run: yarn test

      - name: Lint packages
        run: yarn lint

      - name: Build and check docs
        run: yarn docs

      # Publish to GitHub Packages
      - run: npm run prod-publish
        if: ${{ success() }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@dankreiger'
      - run: yarn lerna exec 'npm publish'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
